version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    groups:
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      browser-tests:
        dependency-type: development
