build:
  environment:
    php:
      version: '8.3'
  dependencies:
    override:
      - composer install --no-interaction --prefer-dist --no-scripts
  nodes:
    analysis:
      tests:
        override:
          - composer test
          - php-scrutinizer-run

checks:
  php: true

filter:
  excluded_paths:
    - tests/
    - scripts/
    - src/resources/
  dependency_paths:
    - vendor/
